FROM repo.keyfactor.com/images/signum-agent:latest
USER root
WORKDIR /etc/keyfactor
# Check the Cosign Release page for the latest releases https://github.com/sigstore/cosign/releases
ARG COSIGN_VERSION="v2.2.4"

# Add the cosign go binary (built with piv-pkcs11 support), to learn more about Cosign checkout https://github.com/sigstore/cosign
RUN curl -LO --silent "https://github.com/sigstore/cosign/releases/download/${COSIGN_VERSION}/cosign-linux-pivkey-pkcs11key-amd64"

RUN mkdir -p /opt/cosign/bin && \
    mv /etc/keyfactor/cosign-linux-pivkey-pkcs11key-amd64 /opt/cosign/bin/cosign && \
    chmod a+x /opt/cosign/bin/cosign && \
    chown -R 10001:0 /opt/cosign && \
    chgrp -R 0 /opt/cosign && \
    chmod -R g=u /opt/cosign

ENV PATH="/opt/cosign/bin:${PATH}"

USER 10001