FROM repo.keyfactor.com/images/signum-agent:latest
USER root
WORKDIR /etc/keyfactor

# OpenSSL Install
# Configure OpenSSL
RUN microdnf update -y && \
    microdnf install openssl openssl-pkcs11 -y && \
    microdnf clean all && \
    rm -rf /var/cache/yum /var/cache/dnf && \
    echo "module:/usr/lib/libkeyfactorpkcs11.so" > /usr/share/p11-kit/modules/keyfactor.module

USER 10001